# Generated by Django 5.2.2 on 2025-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribe_option_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('w', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=5),
        ),
    ]
